/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary-fixed': '#e1e0ff',
        'tertiary-fixed-dim': '#c0c1ff',
        error: '#ba1a1a',
        background: '#faf9f5',
        'on-primary-container': '#7c839b',
        'inverse-on-surface': '#f2f1ed',
        'on-secondary': '#ffffff',
        tertiary: '#000000',
        'on-primary-fixed': '#131b2e',
        'primary-fixed-dim': '#bec6e0',
        'on-tertiary-fixed': '#07006c',
        'on-secondary-container': '#701801',
        'surface-variant': '#e3e2df',
        'error-container': '#ffdad6',
        'on-tertiary-container': '#7073ff',
        'secondary-container': '#fc7f5e',
        'on-tertiary': '#ffffff',
        'surface-container-high': '#e9e8e4',
        'surface-tint': '#565e74',
        'outline-variant': '#c6c6cd',
        'on-surface-variant': '#45464d',
        'on-primary': '#ffffff',
        'on-surface': '#1b1c1a',
        'surface-dim': '#dbdad6',
        'inverse-primary': '#bec6e0',
        'on-background': '#1b1c1a',
        'surface-bright': '#faf9f5',
        outline: '#76777d',
        'on-tertiary-fixed-variant': '#2f2ebe',
        primary: '#000000',
        'on-error-container': '#93000a',
        secondary: '#a33d22',
        'surface-container': '#efeeea',
        'on-secondary-fixed': '#3c0800',
        'on-primary-fixed-variant': '#3f465c',
        'secondary-fixed': '#ffdbd2',
        'tertiary-container': '#07006c',
        'primary-container': '#131b2e',
        'primary-fixed': '#dae2fd',
        'on-error': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed-variant': '#83260d',
        'surface-container-highest': '#e3e2df',
        'surface-container-low': '#f4f4f0',
        surface: '#faf9f5',
        'inverse-surface': '#2f312e',
        'secondary-fixed-dim': '#ffb4a2',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'margin-desktop': '40px',
        'container-max': '1200px',
        'margin-mobile': '16px',
        base: '8px',
      },
      fontFamily: {
        'headline-lg': ['Bricolage Grotesque', 'system-ui', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'headline-lg-mobile': ['Bricolage Grotesque', 'system-ui', 'sans-serif'],
        'headline-md': ['Bricolage Grotesque', 'system-ui', 'sans-serif'],
        'label-sm': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'headline-xl': ['Bricolage Grotesque', 'system-ui', 'sans-serif'],
        'label-bold': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '800' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '500' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '800' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'label-bold': ['14px', { lineHeight: '20px', fontWeight: '700' }],
      },
    },
  },
}
