import type { ImgHTMLAttributes } from 'react';

/** One photo in several widths. Entries come from src/assets/images/index.ts. */
export interface ResponsiveImage {
  src: string;
  srcSet: string;
  width: number;
  height: number;
}

interface ImgProps extends Omit<ImgHTMLAttributes<HTMLImageElement>, 'src' | 'srcSet' | 'width' | 'height'> {
  image: ResponsiveImage;
  /**
   * How wide the image renders, in CSS terms, so the browser can pick the
   * smallest file that fills it — e.g. "(min-width: 1024px) 50vw, 100vw" for
   * a photo that takes half the row on desktop and the full width on a phone.
   * Without this the browser assumes 100vw and over-fetches on wide layouts.
   */
  sizes: string;
  alt: string;
}

/**
 * A photo that ships at the right size for the screen. Every real photo on
 * the site should go through this rather than a bare <img>: it carries the
 * srcset generated by scripts/resize-images.mjs, and the real width/height so
 * the box is reserved before the bytes arrive (zero layout shift).
 *
 * Defaults to lazy loading; pass loading="eager" and fetchPriority="high" for
 * the one image above the fold that is the page's Largest Contentful Paint.
 */
export default function Img({ image, sizes, alt, loading = 'lazy', decoding = 'async', ...rest }: ImgProps) {
  return (
    <img
      src={image.src}
      srcSet={image.srcSet}
      sizes={sizes}
      width={image.width}
      height={image.height}
      alt={alt}
      loading={loading}
      decoding={decoding}
      {...rest}
    />
  );
}
