// GENERATED by scripts/resize-images.mjs — do not edit by hand.
// One entry per photo: the largest file as `src`, every width as `srcSet`,
// and the largest file's real dimensions for the <img> width/height attributes.
import type { ResponsiveImage } from '../../components/Img';

import homeHero1600 from './home-hero-1600.webp';
import homeHero1280 from './home-hero-1280.webp';
import homeHero960 from './home-hero-960.webp';
import homeHero640 from './home-hero-640.webp';
import homeScholarshipPreview1600 from './home-scholarship-preview-1600.webp';
import homeScholarshipPreview1280 from './home-scholarship-preview-1280.webp';
import homeScholarshipPreview960 from './home-scholarship-preview-960.webp';
import homeScholarshipPreview640 from './home-scholarship-preview-640.webp';
import homeCysPreview1600 from './home-cys-preview-1600.webp';
import homeCysPreview1280 from './home-cys-preview-1280.webp';
import homeCysPreview960 from './home-cys-preview-960.webp';
import homeCysPreview640 from './home-cys-preview-640.webp';
import aboutCommunity1600 from './about-community-1600.webp';
import aboutCommunity1280 from './about-community-1280.webp';
import aboutCommunity960 from './about-community-960.webp';
import aboutCommunity640 from './about-community-640.webp';
import aboutFounders1600 from './about-founders-1600.webp';
import aboutFounders1280 from './about-founders-1280.webp';
import aboutFounders960 from './about-founders-960.webp';
import aboutFounders640 from './about-founders-640.webp';
import aboutTeam1600 from './about-team-1600.webp';
import aboutTeam1280 from './about-team-1280.webp';
import aboutTeam960 from './about-team-960.webp';
import aboutTeam640 from './about-team-640.webp';
import programsEmoryGrandPrix1600 from './programs-emory-grand-prix-1600.webp';
import programsEmoryGrandPrix1280 from './programs-emory-grand-prix-1280.webp';
import programsEmoryGrandPrix960 from './programs-emory-grand-prix-960.webp';
import programsEmoryGrandPrix640 from './programs-emory-grand-prix-640.webp';
import programsAcademyInterior1600 from './programs-academy-interior-1600.webp';
import programsAcademyInterior1280 from './programs-academy-interior-1280.webp';
import programsAcademyInterior960 from './programs-academy-interior-960.webp';
import programsAcademyInterior640 from './programs-academy-interior-640.webp';
import impactReportCover1236 from './impact-report-cover-1236.webp';
import impactReportCover989 from './impact-report-cover-989.webp';
import impactReportCover742 from './impact-report-cover-742.webp';
import impactReportCover495 from './impact-report-cover-495.webp';
import impactReportPage11236 from './impact-report-page-1-1236.webp';
import impactReportPage1989 from './impact-report-page-1-989.webp';
import impactReportPage1742 from './impact-report-page-1-742.webp';
import impactReportPage1495 from './impact-report-page-1-495.webp';
import impactReportPage21236 from './impact-report-page-2-1236.webp';
import impactReportPage2989 from './impact-report-page-2-989.webp';
import impactReportPage2742 from './impact-report-page-2-742.webp';
import impactReportPage2495 from './impact-report-page-2-495.webp';
import impactReportPage31236 from './impact-report-page-3-1236.webp';
import impactReportPage3989 from './impact-report-page-3-989.webp';
import impactReportPage3742 from './impact-report-page-3-742.webp';
import impactReportPage3495 from './impact-report-page-3-495.webp';
import impactReportPage41236 from './impact-report-page-4-1236.webp';
import impactReportPage4989 from './impact-report-page-4-989.webp';
import impactReportPage4742 from './impact-report-page-4-742.webp';
import impactReportPage4495 from './impact-report-page-4-495.webp';
import impactReportPage51236 from './impact-report-page-5-1236.webp';
import impactReportPage5989 from './impact-report-page-5-989.webp';
import impactReportPage5742 from './impact-report-page-5-742.webp';
import impactReportPage5495 from './impact-report-page-5-495.webp';
import impactReportPage61236 from './impact-report-page-6-1236.webp';
import impactReportPage6989 from './impact-report-page-6-989.webp';
import impactReportPage6742 from './impact-report-page-6-742.webp';
import impactReportPage6495 from './impact-report-page-6-495.webp';
import impactReportPage71236 from './impact-report-page-7-1236.webp';
import impactReportPage7989 from './impact-report-page-7-989.webp';
import impactReportPage7742 from './impact-report-page-7-742.webp';
import impactReportPage7495 from './impact-report-page-7-495.webp';

export const images = {
  'home-hero': {
    src: homeHero1600,
    srcSet: `${homeHero1600} 1600w, ${homeHero1280} 1280w, ${homeHero960} 960w, ${homeHero640} 640w`,
    width: 1600,
    height: 1066,
  },
  'home-scholarship-preview': {
    src: homeScholarshipPreview1600,
    srcSet: `${homeScholarshipPreview1600} 1600w, ${homeScholarshipPreview1280} 1280w, ${homeScholarshipPreview960} 960w, ${homeScholarshipPreview640} 640w`,
    width: 1600,
    height: 1067,
  },
  'home-cys-preview': {
    src: homeCysPreview1600,
    srcSet: `${homeCysPreview1600} 1600w, ${homeCysPreview1280} 1280w, ${homeCysPreview960} 960w, ${homeCysPreview640} 640w`,
    width: 1600,
    height: 1067,
  },
  'about-community': {
    src: aboutCommunity1600,
    srcSet: `${aboutCommunity1600} 1600w, ${aboutCommunity1280} 1280w, ${aboutCommunity960} 960w, ${aboutCommunity640} 640w`,
    width: 1600,
    height: 1067,
  },
  'about-founders': {
    src: aboutFounders1600,
    srcSet: `${aboutFounders1600} 1600w, ${aboutFounders1280} 1280w, ${aboutFounders960} 960w, ${aboutFounders640} 640w`,
    width: 1600,
    height: 1200,
  },
  'about-team': {
    src: aboutTeam1600,
    srcSet: `${aboutTeam1600} 1600w, ${aboutTeam1280} 1280w, ${aboutTeam960} 960w, ${aboutTeam640} 640w`,
    width: 1600,
    height: 1200,
  },
  'programs-emory-grand-prix': {
    src: programsEmoryGrandPrix1600,
    srcSet: `${programsEmoryGrandPrix1600} 1600w, ${programsEmoryGrandPrix1280} 1280w, ${programsEmoryGrandPrix960} 960w, ${programsEmoryGrandPrix640} 640w`,
    width: 1600,
    height: 1200,
  },
  'programs-academy-interior': {
    src: programsAcademyInterior1600,
    srcSet: `${programsAcademyInterior1600} 1600w, ${programsAcademyInterior1280} 1280w, ${programsAcademyInterior960} 960w, ${programsAcademyInterior640} 640w`,
    width: 1600,
    height: 1066,
  },
  'impact-report-cover': {
    src: impactReportCover1236,
    srcSet: `${impactReportCover1236} 1236w, ${impactReportCover989} 989w, ${impactReportCover742} 742w, ${impactReportCover495} 495w`,
    width: 1236,
    height: 1600,
  },
  'impact-report-page-1': {
    src: impactReportPage11236,
    srcSet: `${impactReportPage11236} 1236w, ${impactReportPage1989} 989w, ${impactReportPage1742} 742w, ${impactReportPage1495} 495w`,
    width: 1236,
    height: 1600,
  },
  'impact-report-page-2': {
    src: impactReportPage21236,
    srcSet: `${impactReportPage21236} 1236w, ${impactReportPage2989} 989w, ${impactReportPage2742} 742w, ${impactReportPage2495} 495w`,
    width: 1236,
    height: 1600,
  },
  'impact-report-page-3': {
    src: impactReportPage31236,
    srcSet: `${impactReportPage31236} 1236w, ${impactReportPage3989} 989w, ${impactReportPage3742} 742w, ${impactReportPage3495} 495w`,
    width: 1236,
    height: 1600,
  },
  'impact-report-page-4': {
    src: impactReportPage41236,
    srcSet: `${impactReportPage41236} 1236w, ${impactReportPage4989} 989w, ${impactReportPage4742} 742w, ${impactReportPage4495} 495w`,
    width: 1236,
    height: 1600,
  },
  'impact-report-page-5': {
    src: impactReportPage51236,
    srcSet: `${impactReportPage51236} 1236w, ${impactReportPage5989} 989w, ${impactReportPage5742} 742w, ${impactReportPage5495} 495w`,
    width: 1236,
    height: 1600,
  },
  'impact-report-page-6': {
    src: impactReportPage61236,
    srcSet: `${impactReportPage61236} 1236w, ${impactReportPage6989} 989w, ${impactReportPage6742} 742w, ${impactReportPage6495} 495w`,
    width: 1236,
    height: 1600,
  },
  'impact-report-page-7': {
    src: impactReportPage71236,
    srcSet: `${impactReportPage71236} 1236w, ${impactReportPage7989} 989w, ${impactReportPage7742} 742w, ${impactReportPage7495} 495w`,
    width: 1236,
    height: 1600,
  },
} satisfies Record<string, ResponsiveImage>;

export type ImageName = keyof typeof images;
